# RESULTS

```{r missing-smus, echo=FALSE, results = T, local = F}

## Message from Dawn on order of results: generally do YUK/Trans, NCA, SCA, FIA, then species SK, PK, CN, CO, CM
# Areas presented North --> South (kind of..). Unsure why for species order. It's the standard for some reason.

source("R/createTablesForReport.R")

library(dplyr)
library(knitr)
library(stringr)


# Pull all SMUs from crosswalkList
all_smus = crosswalkList %>%
  distinct(area, species, smu)

# Identify SMUs **not reported at all** in cu_outlook_records_enriched
reported_smus = cu_outlook_records_enriched %>%
  pull(smu_name) %>%
  str_remove("—.*$") %>%      # remove trailing notes
  str_remove("CHECK:.*$") %>% # remove trailing CHECKs
  str_trim() %>%
  unique()

missing_smus = all_smus %>%
  filter(!smu %in% reported_smus) %>%
  arrange(area, species, smu)

# Display table
if (nrow(missing_smus) == 0) {

  ft <- flextable::flextable(
    data.frame(Message = "All SMUs are accounted for in the survey results.")
  )
  ft <- flextable::set_caption(
    ft,
    caption = "Missing SMUs grouped by Area and Species."
  )
  ft = flextable::autofit(ft)
  ft = flextable::set_table_properties(ft, layout = "autofit")
  ft

} else {
  ft <- flextable::flextable(
    missing_smus,
    col_keys = c("area", "species", "smu")
  )
  ft <- flextable::set_header_labels(
    ft,
    area    = "Area",
    species = "Species",
    smu     = "Missing SMU"
  )
  ft <- flextable::set_caption(
    ft,
    caption = "Use this table to see if there is any missing data that biologists need to submit (i.e., they forgot to submit data for a certain SMU). Note that Odd Year or Even Year Pink data may show up. However, they may not be applicable to the current year, and can be ignored (e.g., there will be no odd year Pink data in 2026). Once you are happy with all the entries, you can turn off this table from showing up in the report, and re-knit the document. This ensures the table numbers in the rest of the document are accurate. You can prevent this table from showing up by going to the 02_results.Rmd file and on line 3 of the code change results = T to results = F in the section that is in between the curly brackets. Doing this tells R Markdown not to include the table in the final output."
  )
  ft = flextable::autofit(ft)
  ft = flextable::set_table_properties(ft, layout = "autofit")
  ft
}

```

```{r missing-cus, echo=FALSE, results = T}

# Get all the reported CUs
reported_cus = cu_outlook_records_enriched %>%
  filter(
    !is.na(cu_outlook_selection),
    !cu_outlook_selection %in% c(
      "CHECK: No data entered",
      "Outlook assigned but no CU specified"
    ),
    !str_detect(cu_outlook_selection, "CHECK")
  ) %>%
  pull(cu_outlook_selection) %>%
  str_split(",") %>%
  unlist() %>%
  str_trim() %>%
  toupper() %>%
  unique()

# Get the list of SMUs to exclude
reported_smus = cu_outlook_records_enriched %>%
  pull(smu_name) %>%
  str_remove("—.*$") %>%
  str_remove("CHECK:.*$") %>%
  str_trim() %>%
  unique()

# Remove the CUs associated with the SMUs that have been reported
reference_cus = crosswalkList %>%
  mutate(
    CU_Code = toupper(str_trim(cu)),
    smu_clean = str_remove(smu, "—.*$") %>% str_remove("CHECK:.*$") %>% str_trim()
  ) %>%
  filter(!smu_clean %in% reported_smus)

# Remove the CUs that were already reported
missing_cus = reference_cus %>%
  filter(!CU_Code %in% reported_cus) %>%
  distinct(area, species, CU_Code, CU_Name = label) %>%
  arrange(area, species, CU_Code)

# Make a table to display info
if (nrow(missing_cus) == 0) {

  ft <- flextable::flextable(
    data.frame(Message = "All CUs are accounted for in the survey results.")
  )

  ft <- flextable::set_caption(
    ft,
    caption = "Missing CUs (Area, Species, Code, Name). Note that CUs belonging to SMUs that have already been reported are excluded."
  )

  ft = flextable::autofit(ft)
  ft = flextable::set_table_properties(ft, layout = "autofit")
  ft

} else {

  ft <- flextable::flextable(
    missing_cus,
    col_keys = c("area", "species", "CU_Code", "CU_Name")
  )

  ft <- flextable::set_header_labels(
    ft,
    area    = "Area",
    species = "Species",
    CU_Code = "CU Code",
    CU_Name = "CU Name"
  )

  ft <- flextable::set_caption(
    ft,
    caption = "Missing CUs (Area, Species, Code, Name). Note that CUs belonging to SMUs that have already been reported are excluded. See the table above for similar warnings and instructions for not including this table in the final version of the report."
  )

  ft = flextable::autofit(ft)
  ft = flextable::set_table_properties(ft, layout = "autofit")
  ft
}
```



## YUKON AND TRANSBOUNDARY AREA

### Sockeye

```{r ytSockeyeTable}

################################################################################
# AREA TABLES
#
# For each Area × Species combination, we attempt to generate a formatted
# SMU table using make_table().
#
# We wrap each call in tryCatch() so that:
# - If no data exists for that combination,
#   the document does NOT fail to knit.
# - Instead, we print a clean message and continue.
#
# This makes the Rmd robust to partial data entry years.
################################################################################


ft = tryCatch(
  make_table("YUKON AND TRANSBOUNDARY", "Sockeye"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```
```{r ytSockeyeFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Sockeye", "YUKON AND TRANSBOUNDARY")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

### Pink

```{r ytPinkTable}

ft = tryCatch(
  make_table("YUKON AND TRANSBOUNDARY", "Pink"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r ytPinkFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Pink", "YUKON AND TRANSBOUNDARY")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

### Chinook

```{r ytChinookTable}

ft = tryCatch(
  make_table("YUKON AND TRANSBOUNDARY", "Chinook"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r ytChinookFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chinook", "YUKON AND TRANSBOUNDARY")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

### Coho

```{r ytCohoTable}

ft = tryCatch(
  make_table("YUKON AND TRANSBOUNDARY", "Coho"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r ytCohoFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Coho", "YUKON AND TRANSBOUNDARY")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


### Chum

```{r ytChumTable}

ft = tryCatch(
  make_table("YUKON AND TRANSBOUNDARY", "Chum"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r ytChumFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chum", "YUKON AND TRANSBOUNDARY")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

## NORTH COAST AREA

### Sockeye

```{r northSockeyeTable}

ft = tryCatch(
  make_table("NORTH COAST", "Sockeye"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}
```

```{r northSockeyeFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Sockeye", "NORTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


### Pink

```{r northPinkTable}

ft = tryCatch(
  make_table("NORTH COAST", "Pink"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}
```

```{r northPinkFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Pink", "NORTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


### Chinook

```{r northChinookTable}

ft = tryCatch(
  make_table("NORTH COAST", "Chinook"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}
```

```{r northChinookFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chinook", "NORTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


### Coho

```{r northCohoTable}

ft = tryCatch(
  make_table("NORTH COAST", "Coho"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}
```

```{r northCohoFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Coho", "NORTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


### Chum

```{r northChumTable}

ft = tryCatch(
  make_table("NORTH COAST", "Chum"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}
```

```{r northChumFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chum", "NORTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

## SOUTH COAST AREA

### Sockeye

```{r scSockeyeTable}

ft = tryCatch(
  make_table("SOUTH COAST", "Sockeye"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r scSockeyeFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Sockeye", "SOUTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

### Pink

```{r scPinkTable}

ft = tryCatch(
  make_table("SOUTH COAST", "Pink"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```


```{r scPinkFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Pink", "SOUTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

### Chinook

```{r scChinookTable}

ft = tryCatch(
  make_table("SOUTH COAST", "Chinook"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}


```

```{r scChinookFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chinook", "SOUTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```



### Coho

```{r scCohoTable}

ft = tryCatch(
  make_table("SOUTH COAST", "Coho"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r scSCohoFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Coho", "SOUTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```



### Chum

```{r scChumTable}

ft = tryCatch(
  make_table("SOUTH COAST", "Chum"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}


```

```{r scChumFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chum", "SOUTH COAST")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


## FRASER AND INTERIOR AREA

### Sockeye

```{r fiaSockeyeTable}

ft = tryCatch(
  make_table("FRASER AND INTERIOR", "Sockeye"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}
```

```{r fiaSockeyeFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Sockeye", "FRASER AND INTERIOR")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


### Pink

```{r fiaPinkEvenTable}

ft = tryCatch(
  make_table("FRASER AND INTERIOR", "Pink"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}
```

```{r fiaPinkFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Pink", "FRASER AND INTERIOR")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```

### Chinook

```{r fiaChinookTable, results = "asis"}

ft = tryCatch(
  make_table("FRASER AND INTERIOR", "Chinook"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r fiaChinookFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chinook", "FRASER AND INTERIOR")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```



### Coho

```{r fiaCohoTable}

ft = tryCatch(
  make_table("FRASER AND INTERIOR", "Coho"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r fiaCohoFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Coho", "FRASER AND INTERIOR")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```


### Chum

```{r fiaChumTable, results = "asis"}

ft = tryCatch(
  make_table("FRASER AND INTERIOR", "Chum"),
  error = function(e){
    print("No data for this species/area combination.")
    return(NULL)
  }
)

if(!is.null(ft)){
  ft
}

```

```{r fiaChumFig, echo=FALSE, fig.align="center", out.width="100%", fig.cap=make_fig_caption("Chum", "FRASER AND INTERIOR")}
# Placeholder figure to anchor the caption with correct styling
op <- par(mar = c(0,0,0,0))
plot.new()
par(op)
```







